# Generated by Django 4.1.3 on 2022-11-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commant',
            field=models.TextField(null=True),
        ),
    ]
